---
# 1. Configuración común para TODOS los servidores
- hosts: all
  become: true
  roles:
    - common
    - security
    - docker
    - monitoring  # Node Exporter (todos se vigilan)
    - vector      # Logs (todos envían logs)

# 2. Configuración específica del Servidor Argus
- hosts: argus_server
  become: true
  roles:
    - argus-stack # <--- ¡NUEVO ROL!


- hosts: gateway
  become: true
  roles:
    - role: gateway  # <--- Nuevo rol



# 3. Configuración de la Fábrica (Forge)
- hosts: builders
  become: true
  vars:
    # 👇 TU REPO YA PUESTO:
    github_repo: "danielorlandooliverdiaz-bit/TechneNexus"
    # 👇 PEGA AQUÍ EL TOKEN QUE ACABAS DE COPIAR:
    github_token: "BXXEBLXYM33RNB6OUW27OP3JPZ2HA"
  roles:
    - github_runner
    - registry







